### ISSUE TITLE
Прописать явно версию

### ISSUE THREAD

**Issue by 240596448** [oscript-library/telegrambot#4]
![image](https://user-images.githubusercontent.com/35220983/98986459-0064cd80-2536-11eb-8057-f14e9af4e021.png)
Может не стоит делать через %ver? А задать явно...?

**Comment by k2589** [comment]
@240596448 сделаю явной при сборке после твоего ПР)

**Comment by pallid** [comment]
ранее когда использовался cicd с гитлаба для публикации пакета это был нормальный вариант
стоит поправить
